### ISSUE TITLE
Default service name does not play well with liquid-fire

### ISSUE THREAD

**Issue by mydea** [knownasilya/ember-toastr#1]
Hi,

I just installed ember-toastr and it works nicely so far. However, with the default service name "notify" it crashes when I use liquid-fire. I changed it in the environment.js to `injectAs: "toast"` and now it works. So, this is quite easily fixable, but I guess it would be nice to choose another default service name, because liquid-fire is a quite popular ember addon, and it is kind of confusing if you install the addon and suddenly nothing works anymore.

**Comment by knownasilya** [comment]
Yes, I've also run into this issue with other notification addons. What kind of default name would you like? `toast`?

This would require a major version change.

**Comment by mydea** [comment]
I'm using `toast`, which in my opinion is quite logical.

**Comment by knownasilya** [comment]
Thanks, I'll make the change.

**Comment by knownasilya** [comment]
Related LF issue https://github.com/ef4/liquid-fire/issues/338

**Comment by knownasilya** [comment]
v1.0.0 released
