### ISSUE TITLE
Toastr dependency defined in dependencies

### ISSUE THREAD

**Issue by ondrejsevcik** [knownasilya/ember-toastr#22]
Hi, first of all, thanks for this awesome addon.

I found that using this addon, I need to specify toastr dependency in my package.json. I think it would make a sense that this dependency would be specified in this addon. Than I don't need to upgrade toastr on my own in my own package. 

What do you think about that?

Thanks,
Ondrej

**Comment by knownasilya** [comment]
The addon should install the dependency for you as long as you use `ember install ember-toastr`.
This method allows you to update the underlying dependency without having to wait for me to release a new version of the addon. This is standard behavior for most addons that wrap other libs.
