### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by benoror** [knownasilya/ember-toastr#23]
What's the proper way to test Toast messages in Acceptance/Integration tests?

I tried the way [ember-cli-flash does it](https://github.com/poteto/ember-cli-flash#acceptance--integration-tests), but the messages never show up while tests are runnin. Any ideas? Thanks!!

**Comment by knownasilya** [comment]
Basically make sure that your `find` method is looking at the correct parent node. The toasts are outside the Ember elements, so default `find` behavior would need to be overwritten to search on `body` or `#toast-container` which is a sibling of `body`.

**Comment by larryh** [comment]
Hi,
Is this still true? I'm using the ember-toastr addon and trying to check for a toast message in an acceptance test.

Unlike the initial question, I can actually see the toast message while the test is running. I included an option to have it display for 10 seconds, which allowed me to see that there is indeed a `div#toast-container` that wraps the whole thing.

But my test was saying that it wasn't found, so I inserted a `waitFor` - which does wait for 5 seconds -  in my test, but that didn't help. (It said: `Promise rejected during "valid request reset-password": waitFor timed out`)

These are the statements in my test. Am I missing something?

`await waitFor('#toast-container', {timeout: 5000});`
`assert.dom('#toast-container').includesText('on how to reset your password')`

**Comment by larryh** [comment]
In case someone else lands here: you need to supply `document` as a second param because toastr notifications are rendered outside of `#ember-testing-container`.

`assert.dom('#toast-container', document).includesText('on how to reset your password');`

This link provides more information:
[Testing Toast](https://thejsguy.com/2018/09/06/custom-qunit-assertions-in-ember.html)

**Comment by knownasilya** [comment]
@larryh think you could submit a pull request adding those basic instructions to the readme?

**Comment by larryh** [comment]
@knownasilya : Well, I tried but was unable to push and thus create a pull request. Not sure why as I entered my correct GitHub password. I think it might be something more than that - maybe you can tell me. 

Regardless, I have attached a screenshot of the error message. And on a more helpful note, here is what I actually entered into the ReadMe, so you can just copy and paste this yourself if you want. As you can see, I entered it right before the "Configuration" section.


## Testing in Acceptance Tests

toastr messages are rendered inside a `div#toast-container`, but outside of `div#ember-testing-container`, where all of the testing action takes place. 

Therefore, you need to supply a second scope parameter of `document` to your `assert.dom(~~~)` calls.
 
For example: `assert.dom('#toast-container', document).includesText('ERROR: Invalid username or password');`
 
## Configuration

These are the default options:

![unable to push](https://user-images.githubusercontent.com/89646/50404057-57f2c800-0769-11e9-80ca-e7565d27a19c.png)

**Comment by uchihamalolan** [comment]
Hey, unlike the initial question I can see the toastr in my tests. But I couldn't handle click events on them. I use mocha for testing

**Comment by knownasilya** [comment]
Thanks @larryh
