### ISSUE TITLE
dependency checker

### ISSUE THREAD

**Issue by bungeye** [knownasilya/ember-toastr#24]
installs ember-cli-babel@5.2.4 installs ember-cli-version-checker@1.3.1 which causes deprecation warning as per:
[https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902](https://github.com/ember-cli/ember-cli-version-checker/issues/48#issuecomment-354912902)

need to update ember-cli-babel dependency

**Comment by knownasilya** [comment]
Give 1.7.1 a try.

**Comment by bungeye** [comment]
Thanks!
