### ISSUE TITLE
How to change default global config options?

### ISSUE THREAD

**Issue by jackiehluo** [knownasilya/ember-toastr#26]
I can override the global options for a specific toast, but is there a way to change the defaults for the whole application?

Thanks!

**Comment by knownasilya** [comment]
See the configuration section https://github.com/knownasilya/ember-toastr#configuration

The example there is the default configuration that is used if you don't set your own.

**Comment by jackiehluo** [comment]
Yes! I saw that—I guess I was wondering, what is `ENV` supposed to indicate?

**Comment by knownasilya** [comment]
Ah, see the code example in this section: https://ember-cli.com/user-guide/#pod-structure

Basically it's setup in `config/environment.js` which has the `ENV` object that can be configured differently for different environment builds of the project.

**Comment by jackiehluo** [comment]
Ahhhhh, makes more sense. Thanks so much!
