### ISSUE TITLE
toastr.subscribe is not working with ember-toastr

### ISSUE THREAD

**Issue by shubmittal** [knownasilya/ember-toastr#27]
I have to provide a callback with a toast notification. I see that ember-toastr is using toastr 2.1.4 which has support for subscribe but it is not working with ember-toastr. I am getting this exception.Query.Deferred exception: toastr.subscribe is not a function TypeError: toastr.subscribe is not a function.

**Comment by knownasilya** [comment]
Are you calling that on the toast service?
