### ISSUE TITLE
Options not working in 2.0.0

### ISSUE THREAD

**Issue by larryh** [knownasilya/ember-toastr#33]
Hi,

First things first: thanks for the great add-on!

Now for the whining :-)

I just upgraded from 1.7.2 to 2.0.0. Was kinda surprised when I didn't see anything at all, but then I RTFM'ed and saw that ember-toastr was no longer auto-injected into routes, controllers, components. So I added the appropriate "inject" statements and all was well.

Except for the appearance and position of the message. I have always had it displayed at the bottom center of the page, along with a progress-bar and close-button. Now it appears at the top-right, without both the progress-bar and close-button. I have attached a screenshot so you can see.

Here is what I have in my `environment.js` file. The only recent addition was the `injectAs: 'toast'`, which wasn't really needed because that is how I referenced it in my code. But I thought maybe adding it would help... but it did not.

Anyway, here are the settings, which have worked for at least a year:

`

 ENV['ember-toastr'] = {
    injectAs: 'toast',
    toastrOptions: {
      progressBar: true,
      closeButton: true,
      positionClass: 'toast-bottom-center'
    }
  };
`

Any thoughts as to how I can get it back down to the bottom center, along with the progress-bar and close-button?

Thanks,
Larry
![Screenshot from 2019-10-10 16-46-52](https://user-images.githubusercontent.com/89646/66609595-1eb40900-eb7f-11e9-891f-189b72569825.png)

**Comment by knownasilya** [comment]
Sounds like a bug, will have a look tomorrow. Thanks!

**Comment by knownasilya** [comment]
Should be fixed with v2.0.1

**Comment by larryh** [comment]
It certainly is - thanks a lot, sir!
