### ISSUE TITLE
Override global option (the 3rd parameter)

### ISSUE THREAD

**Issue by ShenglinGuo** [knownasilya/ember-toastr#5]
Hi, if it is not too much trouble can you implement to allow override of global parameter when calling toastr. Looking at the code, it currently only allow message and title, there does not seems to be any way to pass the overriding option to toastr at moment. 

My specific usage is for some notification, I want to make to stick (not auto dismiss), while for most other notification I still do want them to auto dismiss.

Thank you very much

**Comment by knownasilya** [comment]
Yes, will totally look at implementing something this week

**Comment by knownasilya** [comment]
Released as 1.2.0

**Comment by ShenglinGuo** [comment]
Great, Thank you
