### ISSUE TITLE
Add `clear` and `remove`

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/ember-toastr#8]
Currently available https://github.com/CodeSeven/toastr#other-options but not part of the service

**Comment by Ramblurr** [comment]
Is this on the roadmap? It would be really useful.

**Comment by knownasilya** [comment]
Now that there is interest, it is ;)

**Comment by Ramblurr** [comment]
Huzzah! Thanks.

**Comment by knownasilya** [comment]
You're welcome :+1:
